eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka
---
spring:
  profiles: lazy
activities: to grab a bear,to eat a cookie,to take a nap
---
spring:
  profiles: crazy
activities: to run a marathon, to go hiking
